#!/usr/bin/env python3
# File: ~/Projects/SemiSharp/BackEnd/scripts/tests/regression_test_fast.py
from regression_test_base import *

def run():
    test("[01] Database Connection", lambda: query_one("SELECT 1;"))
    test("[02] Teams Loaded", lambda: assert_positive_count("reference.teams"))
    test("[03] Aliases Loaded", lambda: assert_positive_count("reference.team_aliases"))
    test("[04] Schedule Loaded", lambda: assert_positive_count("schedule.games"))
    test("[05] PFF Ratings Loaded", lambda: assert_positive_count("ratings.pff_power_ratings"))
    test("[06] SIC Scores Loaded", lambda: assert_positive_count("injuries.team_sic_scores"))
    test("[07] Market Events Loaded", lambda: assert_positive_count("market.events"))
    test("[08] Market Spreads Loaded", lambda: assert_positive_count("market.spreads"))
    test("[10] Probability Model Row Count", validate_probability_models_populated)
    test("[11] Probability Two Teams Per Game", validate_probability_row_counts)
    test("[12] Probability Baseline Sums", validate_probability_sums)
    test("[13] Probability Favorite Direction", validate_favorite_probability_direction)
    test("[23] API Health", api_get("/health"))
    test("[24] API Teams", api_get("/teams"))
    test("[25] API Schedule", api_get("/schedule/2026/1"))
    test("[26] API Projections", api_get("/projections/2026/1"))
    test("[27] API Risk", api_get("/risk/2026/1"))
    test("[28] API Market Consensus", api_get("/market/consensus/2026/1"))
    test("[29] API Projection Edge", api_get("/market/projection-edge/2026/1"))
    test("[30] API SIC", api_get("/injuries/sic/2026/1"))
    test("[31] API Strategy Registry", api_get("/strategies"))
    test("[32] API Context GET", api_get("/context/current"))
    test("[33] Strategy Context CIRCA", validate_circa_strategy_context)
    test("[34] Strategy Context STANDARD", validate_standard_strategy_context)
    test("[35] API Strategy Current Week Highest Win", api_get("/strategies/current-week-highest-win/2026/CIRCA", {"rating_week": 1, "hfa_source": "SEMISHARP_2026_RECAL_V1", "entry_id": 1}))
    test("[41] API Strategy Bottom Six Road Fade", api_get("/strategies/bottom-six-road-fade/2026/CIRCA"))
    test("[42] API Strategy Market Arbitrage Exit", api_get("/strategies/market-arbitrage-exit/2026/CIRCA"))
    test("[43] Current Week V2 Contract", validate_current_week_v2_contract)
    test("[44] Current Week V2 Ordering", validate_current_week_v2_ordering)
    test("[45] Current Week V2 Active Leg", validate_current_week_active_leg_only)
    test("[46] Current Week V2 Primary and Alternatives", validate_current_week_primary_consistency)
    test("[47] Current Week V2 Model Versions", validate_current_week_models)
    test("[48] Current Week V2 Used Teams Excluded", validate_current_week_used_teams_excluded)
    test("[54] Season Management Status", api_get("/season-management/status"))
    test("[55] Season Management Valid Picks", api_get("/season-management/entries/1/valid-picks/19"))
    test("[58] API Auth Login Valid", api_post("/auth/login", {"username": "SAS", "password": "SAS"}, 200))
    test("[59] API Auth Login Invalid", api_post("/auth/login", {"username": "SAS", "password": "WRONG"}, 401))
    test("[60] Team Alias List Contract", validate_team_alias_list)
    test("[61] Team Alias Source Summary", validate_team_alias_sources)
    test("[62] Team Alias Resolution", validate_team_alias_resolution)
    test("[63] Team Alias Lifecycle", validate_team_alias_lifecycle)
    test("[64] HFA Read Contract", validate_hfa_read_contract)
    test("[65] HFA Resolver", validate_hfa_resolver)
    test("[66] HFA Update Lifecycle", validate_hfa_update_lifecycle)
    test("[67] Admin Users Contract", validate_admin_users_contract)
    test("[68] Admin Accounts Contract", validate_admin_accounts_contract)
    
    finalize_report()

if __name__ == "__main__":
    run()
    
    test("[45] API Trigger Refresh Market Odds", api_post("/market/refresh-odds", {"season": 2026, "week": 1}))
